spring.application.name=dailymotionminer
server.port=8082

logging.level.aiss.dailymotionminer.controller=DEBUG

dailymotionminer.baseuri=https://api.dailymotion.com

dailymotionminer.maxVideos=10
dailymotionminer.maxComments=10

videominer.uri=http://localhost:8080/videominer/channels
